I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Script/Chapter3/Temporium.rpy", line 291, in script
    if quete_pomme:
  File "game/Script/Chapter3/Temporium.rpy", line 291, in <module>
    if quete_pomme:
NameError: name 'quete_pomme' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Script/Chapter3/Temporium.rpy", line 291, in script
    if quete_pomme:
  File "C:\Thib\Programmation\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Thib\Programmation\RenPy\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Thib\Programmation\RenPy\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Script/Chapter3/Temporium.rpy", line 291, in <module>
    if quete_pomme:
NameError: name 'quete_pomme' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
A Programmer's Journey 0.1
Mon May 13 13:27:11 2024
