I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 118, in script
    show children happy
Exception: Image 'children' does not accept attributes 'happy'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 118, in script
    show children happy
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'children' does not accept attributes 'happy'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
A Programmer's Journey 0.1
Sat Apr 13 19:23:53 2024
